# Generated by Django 4.2.2 on 2023-06-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='release_date',
            field=models.DateField(blank=True, help_text='XXXX-XX-XXのような形式で入力してください', null=True, verbose_name='発売日'),
        ),
    ]
