# Generated by Django 4.2.2 on 2023-06-19 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_goods_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='XXXX-XX-XXのような形式で入力してください', null=True, verbose_name='発売日'),
        ),
    ]
